/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn C_InitI2P(
        argc: ::std::os::raw::c_int,
        argv: *mut *mut ::std::os::raw::c_char,
        appName: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn C_TerminateI2P();
}
unsafe extern "C" {
    pub fn C_StartI2P();
}
unsafe extern "C" {
    pub fn C_StopI2P();
}
unsafe extern "C" {
    pub fn C_RunPeerTest();
}
